default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  pool: 5

development:
  <<: *default
  database: media_transformation_tool_dev
  username: media_transformation
  password: random

test:
  <<: *default
  database: media_transformation_tool_test
  username: media_transformation
  password: random
