default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  pool: 5

development:
  <<: *default
  database: media_transformation_tool_dev
  username: transform
  password: transform

test:
  <<: *default
  database: media_transformation_tool_test
  username: transform
  password: transform

production:
  database: media_transformation_tool_production
  timeout: 5000
  username: <%= ENV['TRANSFORM_USER'] %>
  password:  <%= ENV['TRANSFORM_PASSWORD'] %>