# config/storage.yml
google:
  service: GCS
  project: Transform
  credentials: <%= ENV['GOOGLE_APPLICATION_CREDENTIALS'].as_json %>
  bucket: transform-buck

google_dev:
  service: GCS
  project: Transform
  credentials: <%= Rails.root.join("config/secrets/transform-gcs.json") %>
  bucket: transform-buck